require("henry.plugins-setup")
require("henry.core.options")
require("henry.core.keymaps")
require("henry.core.harpoon")
require("henry.plugins.comment")
require("henry.plugins.nvim-tree")
require("henry.plugins.lualine")
require("henry.plugins.telescope")
require("henry.plugins.treesitter")
require("henry.plugins.fugutive")
require("henry.plugins.autopairs")
require("henry.plugins.gitsigns")
require("henry.plugins.zenmode")
require("henry.plugins.lsp")
require("henry.core.colorscheme")

